### ISSUE TITLE
It worked once, since then it doesn't work anymore

### ISSUE THREAD

**Issue by p1nus** [fifty-six/Scarab#41] opened 2022-02-25 07:40 UTC
![image](https://user-images.githubusercontent.com/97348477/155674861-60b7b520-9dea-4f45-83f5-f45aa3f569e6.png)

**Comment by p1nus** [comment] 2022-02-25 07:44
The first time I opened it, it worked flawlessly. Since then whenever I open it, nothing shows up but this blank screen. It doesn't  show the game directory pop up so I think that's the problem. My friend who has a Steam version of the game (he recently bought it when it was on sale) also got this problem. Any help pls?

**Comment by fifty-six** [comment] 2022-02-27 06:57
Can you give a zip of your `%appdata\HKModInstaller` folder? Is there anything special about your hollow knight installation?

**Comment by fifty-six** [comment] 2022-03-01 22:10
Closing as a duplicate of #47, which has more info anyways.

**Closed by fifty-six** 2022-03-01 22:10 UTC
Labels: bug
