### ISSUE TITLE
Can't get mod links, and some OpenGL and Avolonia issue

### ISSUE THREAD

**Issue by JoMan01** [fifty-six/Scarab#81] opened 2022-06-25 22:06 UTC
Scarab just leaves me on a blank screen after booting it up a second time. I've tried looking other people who have had this issue but none of it seems to work for me. My "HKModInstaller" folder is attached.
![image](https://user-images.githubusercontent.com/47786789/175791759-aad3b4d7-42cd-4d96-914e-ba8e98e6c1dd.png)
![image](https://user-images.githubusercontent.com/47786789/175791774-5789ddfd-90b4-4305-b471-1f4bf992310b.png)
[HKModInstaller.zip](https://github.com/fifty-six/Scarab/files/8985634/HKModInstaller.zip)

**Comment by fifty-six** [comment] 2022-06-26 09:53
Does [this](https://files.catbox.moe/axphx1.zip) do anything different? It might crash without a pop-up box fwiw, but if it does it should have more helpful logs.

**Comment by fifty-six** [comment] 2022-07-05 05:33
This is a duplicate of #47, would love any additional info there though.

**Closed by fifty-six** 2022-07-05 05:33 UTC
Labels: bug, duplicate
