### ISSUE TITLE
Mods "Out of Date"

### ISSUE THREAD

**Issue by LuckyLikesPie** [fifty-six/Scarab#69] opened 2022-05-13 00:49 UTC
I try using some mods like "Custom Knight", "Randomizer 4", and "Tribe of Battle", but they all have an orange thing and say out of date.

**Comment by MikeCZ23** [comment] 2022-05-16 18:53
LanguageSupport is breaking my game

**Comment by fifty-six** [comment] 2022-05-19 08:53
Fairly sure this is a duplicate of #71, though feel free to re-open if it isn't.

**Closed by fifty-six** 2022-05-19 08:53 UTC
Labels: duplicate
